### ISSUE TITLE
Also working with Github

### ISSUE THREAD

**Issue by buchwaldinteractive** [kasp1/dozer-pipelines#1]
Hi there,

Is this also working with github?
My project is a github project and I used to use github desktop for committing etc

Ps: the discord link is not working

**Comment by kasp1** [comment]
It works with any version control system as long as you run the pipeline by Dozer. If you wanted to run it by GitHub Actions (which is a cloud-based alternative to Dozer), perhaps you'd have to adjust the pipeline a little bit (and pay for the runs).

- Git: version control system, a command-line program running locally on your workstation.
- GitHub: a cloud-based portal for hosting Git repositories, one of many.
- GitHub Desktop: a graphical user interface for Git, a program running locally on your workstation, one of many.
- Dozer: a pipeline runner, one of many, but running locally (so that you don't have to pay for cloud-based runners if you are OK running publishing pipelines on your own workstation)
- GitHub Actions: a cloud-based pipeline runner, one of many.

Generally, all pipeline runners store the pipeline scripts, in your Git repository, including Dozer. So Dozer is not only usable with Git repositories hosted on GitHub, but also with any other Git repository hostings.

I'll fix the Discord link, thanks for letting me know :-) https://discord.gg/TwnpfKVzGH

**Comment by buchwaldinteractive** [comment]
Thanks for the insights :)
